//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.586
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessIntelligence.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusinessIntelligence.I18n.ReportsMessages", typeof(ReportsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jan.
        /// </summary>
        public static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oct.
        /// </summary>
        public static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nov.
        /// </summary>
        public static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dec.
        /// </summary>
        public static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feb.
        /// </summary>
        public static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mar.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 days.
        /// </summary>
        public static string _30_days {
            get {
                return ResourceManager.GetString("30_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apr.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mai.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jun.
        /// </summary>
        public static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jul.
        /// </summary>
        public static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aug.
        /// </summary>
        public static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sep.
        /// </summary>
        public static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Commission.
        /// </summary>
        public static string _Commission {
            get {
                return ResourceManager.GetString("%Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oct.
        /// </summary>
        public static string _out {
            get {
                return ResourceManager.GetString("out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apr.
        /// </summary>
        public static string abr {
            get {
                return ResourceManager.GetString("abr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated Month.
        /// </summary>
        public static string Accumulated_Month {
            get {
                return ResourceManager.GetString("Accumulated_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulated Quarter.
        /// </summary>
        public static string Accumulated_Quarter {
            get {
                return ResourceManager.GetString("Accumulated_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievement.
        /// </summary>
        public static string Achievement {
            get {
                return ResourceManager.GetString("Achievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aug.
        /// </summary>
        public static string ago {
            get {
                return ResourceManager.GetString("ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to Partner.
        /// </summary>
        public static string AmountToPartner {
            get {
                return ResourceManager.GetString("AmountToPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentina.
        /// </summary>
        public static string Argentina {
            get {
                return ResourceManager.GetString("Argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssuredPercentage.
        /// </summary>
        public static string AssuredPercentage {
            get {
                return ResourceManager.GetString("AssuredPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Services.
        /// </summary>
        public static string Automotivo {
            get {
                return ResourceManager.GetString("Automotivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Offered Coupon.
        /// </summary>
        public static string AverageCoupon {
            get {
                return ResourceManager.GetString("AverageCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average sold coupon.
        /// </summary>
        public static string AverageSoldCoupon {
            get {
                return ResourceManager.GetString("AverageSoldCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average ticket.
        /// </summary>
        public static string AverageTicket {
            get {
                return ResourceManager.GetString("AverageTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base status.
        /// </summary>
        public static string BaseStatus {
            get {
                return ResourceManager.GetString("BaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beauty.
        /// </summary>
        public static string Beleza_e_Bem_estar {
            get {
                return ResourceManager.GetString("Beleza_e_Bem_estar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between 31 and 180 days.
        /// </summary>
        public static string between_31_and_180_days {
            get {
                return ResourceManager.GetString("between_31_and_180_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazil.
        /// </summary>
        public static string Brasil {
            get {
                return ResourceManager.GetString("Brasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        public static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled 30 Days.
        /// </summary>
        public static string Cancelled30Days {
            get {
                return ResourceManager.GetString("Cancelled30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Pos Accounting.
        /// </summary>
        public static string CancelledPosAccounting {
            get {
                return ResourceManager.GetString("CancelledPosAccounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledPosBilling.
        /// </summary>
        public static string CancelledPosBilling {
            get {
                return ResourceManager.GetString("CancelledPosBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelledPreBilling.
        /// </summary>
        public static string CancelledPreBilling {
            get {
                return ResourceManager.GetString("CancelledPreBilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Pre Billing PU.
        /// </summary>
        public static string CancelledPreBillingPU {
            get {
                return ResourceManager.GetString("CancelledPreBillingPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled yesterday.
        /// </summary>
        public static string CancelledYesterday {
            get {
                return ResourceManager.GetString("CancelledYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chile.
        /// </summary>
        public static string Chile {
            get {
                return ResourceManager.GetString("Chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is active.
        /// </summary>
        public static string CityIsActive {
            get {
                return ResourceManager.GetString("CityIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is top.
        /// </summary>
        public static string CityIsTop {
            get {
                return ResourceManager.GetString("CityIsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commision.
        /// </summary>
        public static string Commision {
            get {
                return ResourceManager.GetString("Commision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitor.
        /// </summary>
        public static string CompetitorName {
            get {
                return ResourceManager.GetString("CompetitorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion rate.
        /// </summary>
        public static string ConversionRate {
            get {
                return ResourceManager.GetString("ConversionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons 30 days.
        /// </summary>
        public static string Coupons30Days {
            get {
                return ResourceManager.GetString("Coupons30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons yesterday.
        /// </summary>
        public static string CouponsYesterday {
            get {
                return ResourceManager.GetString("CouponsYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons / Transactions.
        /// </summary>
        public static string Cupons___Transactions {
            get {
                return ResourceManager.GetString("Cupons_/_Transactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string Cursos_e_Aulas {
            get {
                return ResourceManager.GetString("Cursos_e_Aulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Sales.
        /// </summary>
        public static string DailySales {
            get {
                return ResourceManager.GetString("DailySales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Net revenue.
        /// </summary>
        public static string Dashboard_NetRevenue {
            get {
                return ResourceManager.GetString("Dashboard_NetRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboards.
        /// </summary>
        public static string Dashboards {
            get {
                return ResourceManager.GetString("Dashboards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of week.
        /// </summary>
        public static string DayOfWeek {
            get {
                return ResourceManager.GetString("DayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal.
        /// </summary>
        public static string Deal {
            get {
                return ResourceManager.GetString("Deal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal republication.
        /// </summary>
        public static string DealRepublication {
            get {
                return ResourceManager.GetString("DealRepublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhe das ofertas fechadas.
        /// </summary>
        public static string DealsClosedDt {
            get {
                return ResourceManager.GetString("DealsClosedDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals off line detail.
        /// </summary>
        public static string DealsOffLineDt {
            get {
                return ResourceManager.GetString("DealsOffLineDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals Publication.
        /// </summary>
        public static string DealsPublication {
            get {
                return ResourceManager.GetString("DealsPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals republication.
        /// </summary>
        public static string DealsRepublication {
            get {
                return ResourceManager.GetString("DealsRepublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dec.
        /// </summary>
        public static string dez {
            get {
                return ResourceManager.GetString("dez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        public static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals Closed.
        /// </summary>
        public static string DiscountClosed {
            get {
                return ResourceManager.GetString("DiscountClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals off line.
        /// </summary>
        public static string DiscountOffLine {
            get {
                return ResourceManager.GetString("DiscountOffLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration deals closed.
        /// </summary>
        public static string DurationClosed {
            get {
                return ResourceManager.GetString("DurationClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economized Value.
        /// </summary>
        public static string EconomizedValue {
            get {
                return ResourceManager.GetString("EconomizedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment.
        /// </summary>
        public static string Entret_e_Lazer {
            get {
                return ResourceManager.GetString("Entret_e_Lazer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        public static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Day.
        /// </summary>
        public static string EventDay {
            get {
                return ResourceManager.GetString("EventDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Month1.
        /// </summary>
        public static string EventMonth {
            get {
                return ResourceManager.GetString("EventMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Month.
        /// </summary>
        public static string EventMonthTxt {
            get {
                return ResourceManager.GetString("EventMonthTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Year.
        /// </summary>
        public static string EventYear {
            get {
                return ResourceManager.GetString("EventYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fault Map.
        /// </summary>
        public static string Fault_Map {
            get {
                return ResourceManager.GetString("Fault_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feb.
        /// </summary>
        public static string fev {
            get {
                return ResourceManager.GetString("fev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financeiro.
        /// </summary>
        public static string Financial {
            get {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string Fotografia {
            get {
                return ResourceManager.GetString("Fotografia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurants.
        /// </summary>
        public static string Gastronomia {
            get {
                return ResourceManager.GetString("Gastronomia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrossRevenue.
        /// </summary>
        public static string GrossRevenue {
            get {
                return ResourceManager.GetString("GrossRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross revenue 30 days.
        /// </summary>
        public static string GrossRevenue30Days {
            get {
                return ResourceManager.GetString("GrossRevenue30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross revenue yesterday.
        /// </summary>
        public static string GrossRevenueYesterday {
            get {
                return ResourceManager.GetString("GrossRevenueYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Sales.
        /// </summary>
        public static string GrossSales {
            get {
                return ResourceManager.GetString("GrossSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross sales 30 days.
        /// </summary>
        public static string GrossSales30Days {
            get {
                return ResourceManager.GetString("GrossSales30Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Sales PU Commission.
        /// </summary>
        public static string GrossSalesPUCommission {
            get {
                return ResourceManager.GetString("GrossSalesPUCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross sales yesterday.
        /// </summary>
        public static string GrossSalesYesterday {
            get {
                return ResourceManager.GetString("GrossSalesYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Growth Active Base.
        /// </summary>
        public static string Growth_Active_Base {
            get {
                return ResourceManager.GetString("Growth_Active_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High rescence.
        /// </summary>
        public static string High_rescence {
            get {
                return ResourceManager.GetString("High_rescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in 10 minutes.
        /// </summary>
        public static string in_10_minutes {
            get {
                return ResourceManager.GetString("in_10_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is first date.
        /// </summary>
        public static string IsFirstDate {
            get {
                return ResourceManager.GetString("IsFirstDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsPaymentSoldCoupons.
        /// </summary>
        public static string IsPaymentSoldCoupons {
            get {
                return ResourceManager.GetString("IsPaymentSoldCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jan.
        /// </summary>
        public static string jan {
            get {
                return ResourceManager.GetString("jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jul.
        /// </summary>
        public static string jul {
            get {
                return ResourceManager.GetString("jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jun.
        /// </summary>
        public static string jun {
            get {
                return ResourceManager.GetString("jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicators Panel.
        /// </summary>
        public static string KPI_Panel {
            get {
                return ResourceManager.GetString("KPI_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last deal gross sales.
        /// </summary>
        public static string LastDealGrossSales {
            get {
                return ResourceManager.GetString("LastDealGrossSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LossesAccrual.
        /// </summary>
        public static string LossesAccrual {
            get {
                return ResourceManager.GetString("LossesAccrual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses Cancellation.
        /// </summary>
        public static string LossesCancellation {
            get {
                return ResourceManager.GetString("LossesCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low rescence.
        /// </summary>
        public static string Low_rescence {
            get {
                return ResourceManager.GetString("Low_rescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mai.
        /// </summary>
        public static string mai {
            get {
                return ResourceManager.GetString("mai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mar.
        /// </summary>
        public static string mar {
            get {
                return ResourceManager.GetString("mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market.
        /// </summary>
        public static string Market {
            get {
                return ResourceManager.GetString("Market", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is marketing deal.
        /// </summary>
        public static string MarketingDeal {
            get {
                return ResourceManager.GetString("MarketingDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium rescence.
        /// </summary>
        public static string Medium_rescence {
            get {
                return ResourceManager.GetString("Medium_rescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexico.
        /// </summary>
        public static string México {
            get {
                return ResourceManager.GetString("México", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thousand.
        /// </summary>
        public static string Mil {
            get {
                return ResourceManager.GetString("Mil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than 180 days.
        /// </summary>
        public static string more_than_180_days {
            get {
                return ResourceManager.GetString("more_than_180_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Revenue.
        /// </summary>
        public static string NetRevenue {
            get {
                return ResourceManager.GetString("NetRevenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Sales.
        /// </summary>
        public static string NetSales {
            get {
                return ResourceManager.GetString("NetSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW!.
        /// </summary>
        public static string NEW_ {
            get {
                return ResourceManager.GetString("NEW!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Deals.
        /// </summary>
        public static string NewDiscount {
            get {
                return ResourceManager.GetString("NewDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New partner.
        /// </summary>
        public static string NewPartner {
            get {
                return ResourceManager.GetString("NewPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nov.
        /// </summary>
        public static string nov {
            get {
                return ResourceManager.GetString("nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off line date.
        /// </summary>
        public static string OffLineDate {
            get {
                return ResourceManager.GetString("OffLineDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string Orcado {
            get {
                return ResourceManager.GetString("Orcado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        public static string Orcamento {
            get {
                return ResourceManager.GetString("Orcamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner High Rescence.
        /// </summary>
        public static string PartnerHighRescence {
            get {
                return ResourceManager.GetString("PartnerHighRescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Is Top.
        /// </summary>
        public static string PartnerIsTop {
            get {
                return ResourceManager.GetString("PartnerIsTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Low Rescence.
        /// </summary>
        public static string PartnerLowRescence {
            get {
                return ResourceManager.GetString("PartnerLowRescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Medium Rescence.
        /// </summary>
        public static string PartnerMediumRescence {
            get {
                return ResourceManager.GetString("PartnerMediumRescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner republication.
        /// </summary>
        public static string PartnerRepublication {
            get {
                return ResourceManager.GetString("PartnerRepublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner type.
        /// </summary>
        public static string PartnerType {
            get {
                return ResourceManager.GetString("PartnerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment condition.
        /// </summary>
        public static string PaymentCondition {
            get {
                return ResourceManager.GetString("PaymentCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Produtos {
            get {
                return ResourceManager.GetString("Produtos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promocodes.
        /// </summary>
        public static string Promocodes {
            get {
                return ResourceManager.GetString("Promocodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated.
        /// </summary>
        public static string QTYActivated {
            get {
                return ResourceManager.GetString("QTYActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activations.
        /// </summary>
        public static string QTYActivations {
            get {
                return ResourceManager.GetString("QTYActivations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupons.
        /// </summary>
        public static string QTYCoupons {
            get {
                return ResourceManager.GetString("QTYCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyCustomers.
        /// </summary>
        public static string QTYDailyCustomers {
            get {
                return ResourceManager.GetString("QTYDailyCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals on line.
        /// </summary>
        public static string QTYDiscounts {
            get {
                return ResourceManager.GetString("QTYDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Activity.
        /// </summary>
        public static string QTYHighActivity {
            get {
                return ResourceManager.GetString("QTYHighActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivation.
        /// </summary>
        public static string QTYInactivation {
            get {
                return ResourceManager.GetString("QTYInactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string QTYInactive {
            get {
                return ResourceManager.GetString("QTYInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Activity.
        /// </summary>
        public static string QTYLowActivity {
            get {
                return ResourceManager.GetString("QTYLowActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Customers.
        /// </summary>
        public static string QTYMonthlyCustomers {
            get {
                return ResourceManager.GetString("QTYMonthlyCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customers.
        /// </summary>
        public static string QTYNewCustomers {
            get {
                return ResourceManager.GetString("QTYNewCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Customers.
        /// </summary>
        public static string QTYOldCustomers {
            get {
                return ResourceManager.GetString("QTYOldCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old customers day.
        /// </summary>
        public static string QTYOldCustomersDay {
            get {
                return ResourceManager.GetString("QTYOldCustomersDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old customers month.
        /// </summary>
        public static string QTYOldCustomersMonth {
            get {
                return ResourceManager.GetString("QTYOldCustomersMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactivations.
        /// </summary>
        public static string QTYReactivations {
            get {
                return ResourceManager.GetString("QTYReactivations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers.
        /// </summary>
        public static string QTYSubscribers {
            get {
                return ResourceManager.GetString("QTYSubscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top deal national.
        /// </summary>
        public static string QTYTopDealNational {
            get {
                return ResourceManager.GetString("QTYTopDealNational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top deal regional.
        /// </summary>
        public static string QTYTopDealRegional {
            get {
                return ResourceManager.GetString("QTYTopDealRegional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top ofertas.
        /// </summary>
        public static string QTYTopDeals {
            get {
                return ResourceManager.GetString("QTYTopDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        public static string QTYTransactions {
            get {
                return ResourceManager.GetString("QTYTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real.
        /// </summary>
        public static string Realizado {
            get {
                return ResourceManager.GetString("Realizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real below target.
        /// </summary>
        public static string Realizado_abaixo_da_meta {
            get {
                return ResourceManager.GetString("Realizado_abaixo_da_meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real above target.
        /// </summary>
        public static string Realizado_acima_da_meta {
            get {
                return ResourceManager.GetString("Realizado_acima_da_meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string RegionCountryName {
            get {
                return ResourceManager.GetString("RegionCountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results by no show date.
        /// </summary>
        public static string ResultsByNoShowDate {
            get {
                return ResourceManager.GetString("ResultsByNoShowDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Servicos {
            get {
                return ResourceManager.GetString("Servicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sep.
        /// </summary>
        public static string set {
            get {
                return ResourceManager.GetString("set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deals share.
        /// </summary>
        public static string ShareDiscounts {
            get {
                return ResourceManager.GetString("ShareDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Date.
        /// </summary>
        public static string StatusDate {
            get {
                return ResourceManager.GetString("StatusDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Day.
        /// </summary>
        public static string StatusDay {
            get {
                return ResourceManager.GetString("StatusDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Year.
        /// </summary>
        public static string StatusYear {
            get {
                return ResourceManager.GetString("StatusYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers.
        /// </summary>
        public static string Subscribers {
            get {
                return ResourceManager.GetString("Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total .
        /// </summary>
        public static string T {
            get {
                return ResourceManager.GetString("T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Deals.
        /// </summary>
        public static string TopDiscounts {
            get {
                return ResourceManager.GetString("TopDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top partner.
        /// </summary>
        public static string TopPartner {
            get {
                return ResourceManager.GetString("TopPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tt.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total gross sales.
        /// </summary>
        public static string TotalGrossSales {
            get {
                return ResourceManager.GetString("TotalGrossSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string Trimestre {
            get {
                return ResourceManager.GetString("Trimestre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel.
        /// </summary>
        public static string Turismo {
            get {
                return ResourceManager.GetString("Turismo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Day of Month.
        /// </summary>
        public static string TypeDayOfMonth {
            get {
                return ResourceManager.GetString("TypeDayOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to up to 30 days.
        /// </summary>
        public static string up_to_30_days {
            get {
                return ResourceManager.GetString("up_to_30_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to D.
        /// </summary>
        public static string UpToD {
            get {
                return ResourceManager.GetString("UpToD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Activity.
        /// </summary>
        public static string User_Activity {
            get {
                return ResourceManager.GetString("User_Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visits.
        /// </summary>
        public static string Visits {
            get {
                return ResourceManager.GetString("Visits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
